# Use postgres/example user/password credentials
version: '15.4'

services:

  postgres:
    image: postgres
    container_name: meu-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    container_name: meu-adminer
    ports:
      - 8080:8080
    networks:
      - postgres-network
  
networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:

  